services:
  - type: web
    name: piitrade
    runtime: docker
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: DEBUG
        value: "0"
      - key: ALLOWED_ORIGINS
        value: "https://piitrade.onrender.com"
      - key: SESSION_HTTPS_ONLY
        value: "1"
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_1
        sync: false
      - key: ADMIN_P1
        sync: false
      - key: ADMIN_2
        sync: false
      - key: ADMIN_P2
        sync: false
      - key: PIIDATA
        sync: false
