/* eslint-disable */
export default {
  "key": "create-produce-page",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "loading": "Loading…",
        "loginHeading": "Log in to post your produce",
        "loginSubtitle": "Any Piitrade account can list farm produce — no store or subscription needed.",
        "logIn": "Log In",
        "submittedOneTitle": "Your product was submitted",
        "submittedManyTitle": "products were submitted",
        "pendingApprovalOne": "It’s pending admin approval and will appear on the site once approved — usually within a day.",
        "pendingApprovalMany": "They’ve pending admin approval and will appear on the site once approved — usually within a day.",
        "viewMyListings": "View My Listings",
        "postAnother": "Post Another",
        "pageHeading": "Sell Your Farm Produce",
        "pageSubtitle": "Open to every farmer and seller — no store subscription required. Every submission is reviewed by an admin before it goes live.",
        "oneProduct": "One Product",
        "multipleProducts": "Multiple Products",
        "productLabel": "Product",
        "remove": "Remove",
        "productName": "Product name",
        "productNamePlaceholder": "e.g. Fresh Maize (Grade A)",
        "description": "Description",
        "descriptionPlaceholder": "Quality, harvest date, delivery options…",
        "category": "Category",
        "generalAgriculture": "General Agriculture",
        "condition": "Condition",
        "freshNew": "Fresh / New",
        "usedEquipment": "Used (e.g. equipment)",
        "priceLabel": "Price",
        "priceUnitLabel": "Priced per",
        "unitPerItem": "Item",
        "unitPerKg": "Kg",
        "unitPerTonne": "Tonne",
        "quantityAvailable": "Quantity available",
        "quantityPlaceholder": "e.g. 50",
        "locationLabel": "Location (Uganda)",
        "locationPlaceholder": "e.g. Iganga, Uganda",
        "photosOptional": "Photos (optional)",
        "uploading": "Uploading…",
        "addAnotherProduct": "+ Add Another Product",
        "maxReached": "max",
        "submitting": "Submitting…",
        "submitForApproval": "Submit for Approval",
        "submitMultiple": "Submit",
        "productsForApproval": "Products for Approval",
        "errCategoriesLoading": "Produce categories are still loading — please wait a moment and try again.",
        "errCatsNotSetUp": "Produce categories aren’t set up yet — please try again in a moment or contact support.",
        "errLoadFailed": "Could not load produce categories. Please refresh and try again.",
        "errUploadFailed": "Image upload failed. You can still submit without a photo and add one later.",
        "errSubmitFailed": "Something went wrong while posting your produce. Please try again.",
        "validTitleRequired": "please enter a title.",
        "validDescriptionRequired": "please enter a description.",
        "validPriceRequired": "please enter a valid price.",
        "validQuantityRequired": "please enter a valid quantity.",
        "validLocationRequired": "please enter a location.",
        "yourProductLabel": "Your product"
      },
      "lg": {
        "loading": "Kitikka…",
        "loginHeading": "Yingira okuteeka ebibala byo",
        "loginSubtitle": "Akawunti yonna eya Piitrade eyinza okuteeka ebibala — tewetaagisa dduuka wadde okwewandiisa.",
        "logIn": "Yingira",
        "submittedOneTitle": "Ekintu kyo kiweereddwa",
        "submittedManyTitle": "ebintu byaweereddwa",
        "pendingApprovalOne": "Kirindiridde okukakasibwa omukulembeze era kijja kulabika ku mukutu nga kimaze okukakasibwa — mu bukiikakika olunaku olumu.",
        "pendingApprovalMany": "Birindiridde okukakasibwa omukulembeze era bijja kulabika ku mukutu nga bimaze okukakasibwa — mu bukiikakika olunaku olumu.",
        "viewMyListings": "Laba Ebiwandiikiddwa Byange",
        "postAnother": "Teeka Ekirala",
        "pageHeading": "Tunda Ebibala Byo",
        "pageSubtitle": "Kikwata buli mulimi na mutunzi — tewetaagisa kwewandiisa dduuka. Buli kyaweerezebwa kikebenkanyizibwa omukulembeze nga tekinnalabika.",
        "oneProduct": "Ekintu Kimu",
        "multipleProducts": "Ebintu Bingi",
        "productLabel": "Ekintu",
        "remove": "Ggyawo",
        "productName": "Erinnya ly’Ekintu",
        "productNamePlaceholder": "okugeza: Kasooli Musu (Ekika A)",
        "description": "Obunnyonnyofu",
        "descriptionPlaceholder": "Omutindo, olunaku lw’okukungula, engeri y’okutuusa…",
        "category": "Ekika",
        "generalAgriculture": "Eby’Obulimi Awamu",
        "condition": "Embeera",
        "freshNew": "Kipya",
        "usedEquipment": "Ekikozesebwa (okugeza ebyuma)",
        "priceLabel": "Omuwendo",
        "priceUnitLabel": "Omuwendo gwa buli",
        "unitPerItem": "Ekintu",
        "unitPerKg": "Kg",
        "unitPerTonne": "Tona",
        "quantityAvailable": "Obungi obuliwo",
        "quantityPlaceholder": "okugeza: 50",
        "locationLabel": "Ekifo (Uganda)",
        "locationPlaceholder": "okugeza: Iganga, Uganda",
        "photosOptional": "Ebifaananyi (si bya bwe tteekwa)",
        "uploading": "Kiweebwa…",
        "addAnotherProduct": "+ Yongera Ekintu Ekirala",
        "maxReached": "ekisinga",
        "submitting": "Kiweereza…",
        "submitForApproval": "Weereza Okukakasibwa",
        "submitMultiple": "Weereza",
        "productsForApproval": "Ebintu Okukakasibwa",
        "errCategoriesLoading": "Ebika by’ebibala bikyaleeta — linda akatono oddemu ogezeeko.",
        "errCatsNotSetUp": "Ebika by’ebibala tebinnateekebwawo — ddamu ogezeeko oluvannyuma oba tukwatagane n’obuyambi.",
        "errLoadFailed": "Tetuyinza kuleeta bika by’ebibala. Ddamu oteekemu olupapula oddemu ogezeeko.",
        "errUploadFailed": "Okuweereza ekifaananyi tekulabise. Osobola okuweereza awatali kifaananyi n’oyongera oluvannyuma.",
        "errSubmitFailed": "Ekintu tekigenze bulungi ng’oweereza ebibala byo. Ddamu ogezeeko.",
        "validTitleRequired": "teeka erinnya.",
        "validDescriptionRequired": "teeka obunnyonnyofu.",
        "validPriceRequired": "teeka omuwendo omutuufu.",
        "validQuantityRequired": "teeka obungi obutuufu.",
        "validLocationRequired": "teeka ekifo.",
        "yourProductLabel": "Ekintu kyo"
      },
      "sw": {
        "loading": "Inapakia…",
        "loginHeading": "Ingia kuweka mazao yako",
        "loginSubtitle": "Akaunti yoyote ya Piitrade inaweza kuorodhesha mazao — hakuna duka au usajili unaohitajika.",
        "logIn": "Ingia",
        "submittedOneTitle": "Bidhaa yako imewasilishwa",
        "submittedManyTitle": "bidhaa zimewasilishwa",
        "pendingApprovalOne": "Inasubiri idhini ya msimamizi na itaonekana kwenye tovuti mara itakapoidhinishwa — kwa kawaida ndani ya siku moja.",
        "pendingApprovalMany": "Zinasubiri idhini ya msimamizi na zitaonekana kwenye tovuti mara zitakapoidhinishwa — kwa kawaida ndani ya siku moja.",
        "viewMyListings": "Ona Orodha Zangu",
        "postAnother": "Weka Nyingine",
        "pageHeading": "Uza Mazao Yako ya Shambani",
        "pageSubtitle": "Wazi kwa kila mkulima na muuzaji — hakuna usajili wa duka unaohitajika. Kila uwasilishaji hukaguliwa na msimamizi kabla ya kuonekana.",
        "oneProduct": "Bidhaa Moja",
        "multipleProducts": "Bidhaa Nyingi",
        "productLabel": "Bidhaa",
        "remove": "Ondoa",
        "productName": "Jina la Bidhaa",
        "productNamePlaceholder": "mf. Mahindi Mabichi (Daraja A)",
        "description": "Maelezo",
        "descriptionPlaceholder": "Ubora, tarehe ya mavuno, chaguo za usafirishaji…",
        "category": "Kategoria",
        "generalAgriculture": "Kilimo kwa Ujumla",
        "condition": "Hali",
        "freshNew": "Mpya / Bichi",
        "usedEquipment": "Vilivyotumika (mf. vifaa)",
        "priceLabel": "Bei",
        "priceUnitLabel": "Bei kwa kila",
        "unitPerItem": "Bidhaa",
        "unitPerKg": "Kg",
        "unitPerTonne": "Tani",
        "quantityAvailable": "Kiasi Kinachopatikana",
        "quantityPlaceholder": "mf. 50",
        "locationLabel": "Mahali (Uganda)",
        "locationPlaceholder": "mf. Iganga, Uganda",
        "photosOptional": "Picha (si lazima)",
        "uploading": "Inapakiwa…",
        "addAnotherProduct": "+ Ongeza Bidhaa Nyingine",
        "maxReached": "kiwango cha juu",
        "submitting": "Inawasilishwa…",
        "submitForApproval": "Wasilisha kwa Idhini",
        "submitMultiple": "Wasilisha",
        "productsForApproval": "Bidhaa kwa Idhini",
        "errCategoriesLoading": "Kategoria za mazao bado zinapakia — tafadhali subiri kidogo kisha jaribu tena.",
        "errCatsNotSetUp": "Kategoria za mazao bado hazijawekwa — tafadhali jaribu tena baadaye au wasiliana na msaada.",
        "errLoadFailed": "Imeshindwa kupakia kategoria za mazao. Tafadhali onyesha upya na ujaribu tena.",
        "errUploadFailed": "Upakiaji wa picha umeshindwa. Bado unaweza kuwasilisha bila picha na kuongeza baadaye.",
        "errSubmitFailed": "Hitilafu imetokea wakati wa kuweka mazao yako. Tafadhali jaribu tena.",
        "validTitleRequired": "tafadhali weka jina.",
        "validDescriptionRequired": "tafadhali weka maelezo.",
        "validPriceRequired": "tafadhali weka bei sahihi.",
        "validQuantityRequired": "tafadhali weka kiasi sahihi.",
        "validLocationRequired": "tafadhali weka mahali.",
        "yourProductLabel": "Bidhaa yako"
      },
      "ach": {
        "loading": "Tye ka gamo…",
        "loginHeading": "Donj i akawunti me keto jami me pur ni",
        "loginSubtitle": "mo keken Piitrade akawunti can ket farm produce — pe duka or kwako needed.",
        "logIn": "Donjo",
        "submittedOneTitle": "Gin ni o-cwalo",
        "submittedManyTitle": "jami were submitted",
        "pendingApprovalOne": "It’s orindo ladit yubo and will appear on the website once oyubo — usually within a nino.",
        "pendingApprovalMany": "They’ve orindo ladit yubo and will appear on the website once oyubo — usually within a nino.",
        "viewMyListings": "Nen jami ma iya cato",
        "postAnother": "ket mokene",
        "pageHeading": "Cat jami me pur ni",
        "pageSubtitle": "yab to every farmer and lacat — pe duka kwako myero. Every submission is renened by an ladit makato it goes live.",
        "oneProduct": "Gin acel",
        "multipleProducts": "Jami mapol",
        "productLabel": "Gin",
        "remove": "Golo",
        "productName": "Nying gin",
        "productNamePlaceholder": "e.g. Fresh Maize (Grade A)",
        "description": "Nyonyo matut",
        "descriptionPlaceholder": "Quality, harvest nino, cweyo options…",
        "category": "Kit",
        "generalAgriculture": "Pur ma dok i kom",
        "condition": "Kit ma tye",
        "freshNew": "Nyen / Maleng",
        "usedEquipment": "Moketo (calo jami me tic)",
        "priceLabel": "Wel",
        "priceUnitLabel": "Priced per",
        "unitPerItem": "Item",
        "unitPerKg": "Kg",
        "unitPerTonne": "Tonne",
        "quantityAvailable": "Wel jami ma tye",
        "quantityPlaceholder": "e.g. 50",
        "locationLabel": "Kabedo (Uganda)",
        "locationPlaceholder": "e.g. Iganga, Uganda",
        "photosOptional": "Cal (pe me gire)",
        "uploading": "Tye ka keto…",
        "addAnotherProduct": "+ med mokene gin",
        "maxReached": "mapol",
        "submitting": "Tye ka cwal…",
        "submitForApproval": "Cwal me yubo",
        "submitMultiple": "Cwal",
        "productsForApproval": "Jami ma orindo me yubo",
        "errCategoriesLoading": "Produce kit are still tye ka gamo — Tim ber iriw manok and try again.",
        "errCatsNotSetUp": "Produce kit aren’t set up yet — Tim ber gin doki in a moment or lok ki kony.",
        "errLoadFailed": "Could not load produce kit. Please refresh and try again.",
        "errUploadFailed": "cal ket failed. in can still submit without a cal and med one later.",
        "errSubmitFailed": "Something went wrong while posting ni produce. Tim ber gin doki.",
        "validTitleRequired": "tim ber ket nying.",
        "validDescriptionRequired": "tim ber ket nyonyo matut.",
        "validPriceRequired": "tim ber ket wel ma atir.",
        "validQuantityRequired": "tim ber ket wel jami ma atir.",
        "validLocationRequired": "tim ber ket kabedo.",
        "yourProductLabel": "Gin ni"
      }
    }
  },
  "location": "local",
  "localId": "create-produce-page::local::app/listings/create-produce/createProduce.content.ts",
  "filePath": "app/listings/create-produce/createProduce.content.ts"
} as const;
